export type ProdutoHiper = {
  altura: number;
  ativo: boolean;
  categoria: string | null;
  categoriaDoProdutoId: string | null;
  codigo: number;
  codigoDeBarras: string;
  comprimento: number;
  cor: string;
  descricao: string | null;
  grade: boolean;
  id: string;
  imagem: string;
  imagensAdicionais: string[];
  largura: number;
  marca: string | null;
  ncm: string;
  nome: string;
  peso: number;
  preco: number;
  produtoPrimarioId: string;
  quantidadeEmEstoque: number;
  quantidadeMinimaEmEstoque: number;
  removido: boolean;
  tamanho: string;
  unidade: string;
  variacao: string | null;
  variacaoAtiva: boolean;
};
